FROM registry.centos.org/centos:8

WORKDIR /home
RUN dnf -y update
RUN yum -y install dnf-plugins-core && yum -y config-manager --set-enabled powertools
RUN dnf install  -y gpgme-devel libseccomp-devel.x86_64 libseccomp-devel.x86_64 systemd-devel git make go libassuan-devel
ENV PKG_CONFIG_PATH="/usr/lib/pkgconfig"

ENV BRANCH="hotfix/v2.2.2"
ENV TARGET_DIR="/home/bin"
COPY install.sh /home/install.sh

ENTRYPOINT ["/home/install.sh"]
